# Generated by scripts/generate-formula.sh for v1.0.0-beta.5. Do not edit by hand.
class Wt < Formula
  desc "Git worktree manager with an interactive, PR-aware TUI"
  homepage "https://github.com/tito0224/wt"
  version "1.0.0-beta.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_darwin_arm64.tar.gz"
      sha256 "613e425a68441b6bcba5800137d6982615ad8d1b6cb119cf98f1eed027489138"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_darwin_amd64.tar.gz"
      sha256 "a680255da867237dd2517dcd021096389ef92d8515615d836b74376ffbc14127"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_linux_arm64.tar.gz"
      sha256 "de8be9501b1cafe71fc5a459b52c481c01126c32b494417d07b9eaa4f4d6b7f6"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_linux_amd64.tar.gz"
      sha256 "8f2656d1a672c82b1b11b4a06eb6d14567296f6a8ad58bfe5604092f41f788b2"
    end
  end

  def install
    bin.install "wt"
  end

  def caveats
    <<~EOS
      To enable cd-in-place shell integration, run:
        wt shell install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wt --version")
  end
end
