# Generated by scripts/generate-formula.sh for v1.0.0-beta.4. Do not edit by hand.
class Wt < Formula
  desc "Git worktree manager with an interactive, PR-aware TUI"
  homepage "https://github.com/tito0224/wt"
  version "1.0.0-beta.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.4/wt_v1.0.0-beta.4_darwin_arm64.tar.gz"
      sha256 "40522fc69241039e28912671beb52bb97f2f31dd4aa30c341863dae21edc63ab"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.4/wt_v1.0.0-beta.4_darwin_amd64.tar.gz"
      sha256 "27fead1eb8f56174ea5f70ede96cd3cd050d02614ac5a4c2f49a2a900ad2da0a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.4/wt_v1.0.0-beta.4_linux_arm64.tar.gz"
      sha256 "82e35515642f33eed288fe8703eac65a1acce020f8aff7c4032527a422cd3352"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.4/wt_v1.0.0-beta.4_linux_amd64.tar.gz"
      sha256 "74461463ffc4373d83cb3cec2755280de58063bf96ae4220dbe70fda65030434"
    end
  end

  def install
    bin.install "wt"
  end

  def caveats
    <<~EOS
      To enable cd-in-place shell integration, run:
        wt shell install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wt --version")
  end
end
