# Generated by scripts/generate-formula.sh for v1.0.0-beta.5. Do not edit by hand.
class Wt < Formula
  desc "Git worktree manager with an interactive, PR-aware TUI"
  homepage "https://github.com/tito0224/wt"
  version "1.0.0-beta.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_darwin_arm64.tar.gz"
      sha256 "ea32b1f3a0909e9718ccd28705332c86e75a59d92766e1cc87ba4cb4c1477677"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_darwin_amd64.tar.gz"
      sha256 "6f47a6123b65f5380a838273069905f19cf851cb30269f7f11c0ce10dc1aae3f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_linux_arm64.tar.gz"
      sha256 "23773e6145657589f4131d2fe53e713ba106453cdad51ec131177e0a21e8827d"
    end
    on_intel do
      url "https://github.com/tito0224/wt/releases/download/v1.0.0-beta.5/wt_v1.0.0-beta.5_linux_amd64.tar.gz"
      sha256 "1b45263fef2fc199a28004aef6d00012dfb20156526fd7aebde341919f9014f3"
    end
  end

  def install
    bin.install "wt"
  end

  def caveats
    <<~EOS
      To enable cd-in-place shell integration, run:
        wt shell install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wt --version")
  end
end
